apiVersion: v1
kind: Service
metadata:
  name: locust-master
spec:
  selector:
    app: locust
    role: master
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      name: http
    - protocol: TCP
      port: 5557
      targetPort: 5557
      name: locust-task
    - protocol: TCP
      port: 5558
      targetPort: 5558
      name: locust-health
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
      role: master
  template:
    metadata:
      labels:
        app: locust
        role: master
    spec:
      containers:
        - name: locust
          image: my-locust-image
          imagePullPolicy: Never
          args: ["-f", "/locustfile.py", "--master", "--host=http://fastapi-service:8000"]
          ports:
            - containerPort: 8089
            - containerPort: 5557
            - containerPort: 5558
